### ISSUE TITLE
PAM account function broken in 20230919.00

### ISSUE THREAD

**Issue by jonsulman** [GoogleCloudPlatform/guest-oslogin#123] opened 2023-11-14 19:54 UTC
We use the PAM account function as documented in the README, but as of the google-compute-engine-oslogin-20231004 release, PAM account lookups using the pam_oslogin_login.so module fail with the `error: PAM unable to resolve symbol: pam_sm_acct_mgmt`.

I see the pam_sm_acct_mgmt function was removed in #116. This change broke functionality that we depend on. Can it be reversed?

For reference, our pam configuration uses code like this to apply different policies to oslogin vs local or ldap user accounts (e.g. restricting user account login based on group membership).

```
account     [success=1 default=ignore]                   pam_oslogin_login.so
account     substack                                     user-policy
```

The project README documents how to use both the pam_oslogin_login.so and pam_oslogin_admin.so modules in the PAM account stack, so I would expect this functionality to still be supported. (https://github.com/GoogleCloudPlatform/guest-oslogin/tree/master#pam-modules)

**Comment by dorileo** [comment] 2023-11-21 22:09
Hi @jonsulman 

Indeed we forgot to update the documentation. Why do you need the `pam_oslogin_login.so` in the `account` stack? You mention `...our pam configuration uses code like this to apply different policies to oslogin vs local...` can you expand this and further describe your use case? Can you accomplish the same without the `pam_oslogin_login.so` in the `account` stack?

Thanks,
Leo

**Comment by jonsulman** [comment] 2023-11-28 17:15
We support logins to Linux systems both by users defined in Active Directory (via sssd integration) and OS Login. When Active Directory users log in we use `pam_access.so` to restrict access based on group membership and `pam_succeed_if.so` to further restrict based on user name pattern. Neither of these checks work on logins by OS Login users because OS Login users aren't part of the Active Directory groups and they have a different username style from our enterprise standard. In order to run these checks on Active Directory users but not on OS Login users we need to distinguish between these user types, and `pam_oslogin_login.so` is the most accurate way of doing so.

The alternative is to use a username match with `pam_succeed_if.so` -- i.e. identifying Service Accounts logging on with oslogin with this rule: `pam_succeed_if.so user =~ sa_*`. However, this assumes no other users attempting to log in would have usernames matching this pattern..

**Comment by glaubitz** [comment] 2024-01-11 18:05
One of our customers reported this regression on SUSE Linux Enterprise as well. They can no longer log in using Active Directory.

What is the recommend configuration change to restore the login functionality through Active Directory other reverting the changes in #116?

**Comment by gygitlab** [comment] 2024-01-15 15:08
On all of our Ubuntu GCP environments today we've noticed `sudo su` suddenly failing across them all.

We log in with our accounts via oslogin. The error logs point to the removal of `pam_oslogin_admin.so` as the problem:

```
sudo su
su: Module is unknown

/var/log/auth.log:
Jan 15 14:58:07 vm-name: PAM unable to dlopen(pam_oslogin_admin.so): /lib/security/pam_oslogin_admin.so: cannot open shared object file: No such file or directory
Jan 15 14:58:07 vm-name: PAM adding faulty module: pam_oslogin_admin.so
```

I would consider this a significant regression and will likely be impacting many users soon enough presuming the rollout of this change is affecting existing instances that upgrade now. Happy to raise a separate issue if needed here or elsewhere.

**Comment by dorileo** [comment] 2024-01-16 19:23
Hi @gygitlab,

The problem you are reporting is a different issue, it's that guest-agent is not cleaning up the previous configuration. Thanks for raising it and creating a separate report to it.

Thanks,
Leo

**Comment by dorileo** [comment] 2024-01-16 19:27
For the reported issue I'm considering adding an account management implementation to: "report if such an user is managed by osLogin (or if it's a known osLogin user)" so it could be used in custom rules like the one mentioned by @jonsulman - not not having guest-agent managing it, only exposing the functionality for users to combine it with their own custom configurations (again, not managed by guest-agent).

**Comment by gerry-tock** [comment] 2024-01-26 16:42
I don't think I'm having the exact same issue, because I can see that `pam_oslogin_login.so` is not being used on my VMs, but my issue may be related to the changes in the way oslogin operates. 

On some of my VMs, I can ssh into them and also gain sudo access without a password. On others, I can ssh into them, but when I try to gain sudo access, I am prompted for a password. Nothing stands out about these VMs. Some have been up for 3 years....others a few months. 

The workaround for us right now is to have someone manually created the user file in /var/google-sudoers.d/. But there are some VMs where none of us have access to sudo to use this workaround. 

Something is broken in whatever mechanism syncs our IAM permissions to being a sudo user or not. Some reading brought me [here](https://chromium.googlesource.com/external/github.com/GoogleCloudPlatform/compute-image-packages/+/refs/tags/20190124/google_compute_engine_oslogin/README.md#pam-module), but after seeing this issue, it seems like I'm chasing something that does not exist anymore.

**Comment by HMKRL** [comment] 2024-02-02 08:41
Similar issue here. Two of our GCP ubuntu instance suddenly became unable to login.

No SSH from web, no SSH from gcloud command line, even user creation from startup-script won't work (**basically locked-out from these VM**).

Mounted these VM disks to other instance, found a bunch of PAM errors in `auth.log` when trying to login:
`PAM unable to dlopen(pam_oslogin_admin.so): /lib/security/pam_oslogin_admin.so: cannot open shared object file: No such file or directory`

**Comment by marciobasel** [comment] 2024-02-02 12:38
> Similar issue here. Two of our GCP ubuntu instance suddenly became unable to login.
> 
> No SSH from web, no SSH from gcloud command line, even user creation from startup-script won't work (**basically locked-out from these VM**).
> 
> Mounted these VM disks to other instance, found a bunch of PAM errors in `auth.log` when trying to login: `PAM unable to dlopen(pam_oslogin_admin.so): /lib/security/pam_oslogin_admin.so: cannot open shared object file: No such file or directory`

I can confirm I have the exact same issue. 

And I can replicate it very easily. Here are the steps:
- Create a fresh VM with our custom Ubuntu 20.04 which still has the 20200925.00-0ubuntu3~20.04.0 version of google-compute-engine-oslogin installed.
- Run this: `sudo apt-get install google-compute-engine-oslogin`
- Version 20231004.00-0ubuntu1~20.04.2 gets installed
- Completely broken, unreachable and same /var/log/auth.log entries. Exactly as HMKRL commented.

This seems quite concerning.

**Comment by gygitlab** [comment] 2024-02-02 13:01
> @gygitlab did you find a solution for this? For us it not only affects su command, but breaks completely SSH connection.

Google support did share with me the following to the `sudo su` issue I had:

>>>
**Workaround**: 

Edit the `/etc/pam.d/su` file and remove the following block:

```
# Added by Google Compute Engine OS Login.
account    [success=bad ignore=ignore] pam_oslogin_login.so
```
>>>

I couldn't say about the SSH issues you are seeing though sorry.

**Comment by marciobasel** [comment] 2024-02-02 13:06
Thank you @gygitlab. I can confirm the following:
1- Edit /etc/pam.d/sshd 
2- Commenting out the line:
`#account    [success=ok ignore=ignore default=die] pam_oslogin_login.so`
3- SSH immediately works again.

I am still not sure if this is just a quick fix, or it is a proper solution.

**Comment by dorileo** [comment] 2024-02-02 17:57
@gerry-tock what OS are you using? can you check the guest-agent and oslogin package versions installed in your system?

**Comment by dorileo** [comment] 2024-02-02 17:59
@HMKRL can you share your vms `/etc/sudo.d/ssh` and `/etc/sudo.d/su` files?

**Comment by dorileo** [comment] 2024-02-02 18:02
hi @marciobasel in your case you should update also guest-agent package, canonical is working to fix their dependencies in the packages and avoid this case you are describing, but until they do you will need to guarantee that when you update oslogin you also update guest-agent.

**Comment by dorileo** [comment] 2024-02-02 18:04
Hi @marciobasel your case is different to @gygitlab.

**Comment by dorileo** [comment] 2024-02-02 18:06
@gygitlab for your case we are preparing a fix [here](https://github.com/GoogleCloudPlatform/guest-agent/pull/348). It will be available on next release - although guest-agent will never recreate the line you commented out.

**Comment by HMKRL** [comment] 2024-02-02 19:02
> @HMKRL can you share your vms `/etc/sudo.d/ssh` and `/etc/sudo.d/su` files?

Neither of these files exists in our VM.

I Fix the problem now by commenting out oslogin related lines in `/etc/pam.d/sshd` (they're different in two VMs)

Both VM are running `Ubuntu 20.04`, `oslogin@20231004.00-0ubuntu1` and `guest-agent` not installed.

VM No.1:
```
# Added by Google Compute Engine OS Login.
#account    requisite    pam_oslogin_login.so
# Added by Google Compute Engine OS Login.
#account    optional     pam_oslogin_admin.so
```

VM No.2:
```
#### Google OS Login control. Do not edit this section. ####
#account    [success=ok ignore=ignore default=die] pam_oslogin_login.so
#account    [success=ok default=ignore] pam_oslogin_admin.so
```

**Comment by dorileo** [comment] 2024-02-02 21:21
hi @HMKRL 

> Neither of these files exists in our VM.

Sorry, I meant `/etc/pam.d/ssh` and `/etc/pam.d/su` as you figured out.

> Both VM are running Ubuntu 20.04, oslogin@20231004.00-0ubuntu1 and guest-agent not installed

I believe you removed it yourself, right?

> Edit: I've done some reboots and it seems fine now ( probably because guest-agent not installed?), should I install guest-agent@20231004.02-0ubuntu1~20.04.3 or it'll be better to wait for the updated version?

You can install `guest-agent@20231004.02-0ubuntu1~20.04.3`, it knows how to manage the current format configuration (compatible with `oslogin@20231004.00-0ubuntu1`).

**Comment by marciobasel** [comment] 2024-02-05 10:07
> hi @marciobasel in your case you should update also guest-agent package, canonical is working to fix their dependencies in the packages and avoid this case you are describing, but until they do you will need to guarantee that when you update oslogin you also update guest-agent.

Hi @dorileo many thanks!! I can confirm that running the following command fixes the problem:
`apt-get install google-guest-agent`

The thing is, this wasn't an update, but a fresh install of the package. It wasn't present on the custom Ubuntu image. And everything was working fine. Shouldn't then google-guest-agent be a dependency of google-osconfig-agent?

**Comment by glaubitz** [comment] 2024-02-06 09:31
@dorileo What are the plans to address the original issues? We have customers that can no longer login is as AD user using SSH.

**Comment by dorileo** [comment] 2024-02-06 20:34
Hi @marciobasel 

> The thing is, this wasn't an update, but a fresh install of the package. It wasn't present on the custom Ubuntu image. And > everything was working fine.

I'm pretty sure Canonical ships both packages in their standard gce images, I'd check how this "custom" image is being created.

>  Shouldn't then google-guest-agent be a dependency of google-osconfig-agent?

Yes, it should. We are working with Canonical to address this issue on their side.

Thanks,
Leo

**Comment by dorileo** [comment] 2024-02-06 20:37
Hi @glaubitz 

> @dorileo What are the plans to address the original issues? We have customers that can no longer login is as AD user using SSH.

We are working on what I [commented](https://github.com/GoogleCloudPlatform/guest-oslogin/issues/123#issuecomment-1894377309) back in this bug. I'll bring back the pam module so users can use it in their custom configuration - although google-guest-agent will not use or configure it by default (for the supported use cases).

Thanks,
Leo

**Comment by dorileo** [comment] 2024-02-06 20:40
Hi @gerry-tock 

> On some of my VMs, I can ssh into them and also gain sudo access without a password. On others, I can ssh into them, but > when I try to gain sudo access, I am prompted for a password. Nothing stands out about these VMs. Some have been up 
> for 3 years....others a few months.

This behavior makes me thing that your VMs might be with different configuration, the versions you mentioned in another comment (google-guest-agent 20231004.02-0ubuntu1~20.04.3 and google-compute-engine-oslogin 20231004.00-0ubuntu1~20.04.2) should work. Check your VMs and see if they are with the same combination (I'd expect they aren't), if the versions are as you mentioned sudo should work.

Please let me know about your findings.

Thanks,
Leo

**Comment by marciobasel** [comment] 2024-02-07 08:51
> > Shouldn't then google-guest-agent be a dependency of google-osconfig-agent?
> 
> Yes, it should. We are working with Canonical to address this issue on their side.
Much appreciated @dorileo
Is there any place where we can track progress of this?

**Comment by dorileo** [comment] 2024-02-07 18:42
Hi @gerry-tock 

> BUT the VM that I had an issue with is suddenly working. The /var/google-sudoers.d/ directory is now being automatically updated as we ssh into the VM and therefore we have sudo access now.

That's expected, we worked with Canonical to have the issue fixed, `unattended-upgrade` might have picked the new versions and installed to your failing VM.

Thanks,
Leo

**Comment by marciobasel** [comment] 2024-02-13 09:50
@dorileo is there any place where we can track the progress of Canonical fixing the dependency issue?
We would like to know if we roll-out manual measures to fix this or we can wait a reasonable amount of time for Canonical to fix it.
Thanks!

**Comment by dorileo** [comment] 2024-03-07 00:51
@marciobasel it was already rolled out.

Thanks,
Leo

**Comment by dorileo** [comment] 2024-03-07 01:28
Hi @jonsulman

Do you have the means to test [this PR](https://github.com/GoogleCloudPlatform/guest-oslogin/pull/133) and let me know that it works as expected on you configuration?

Thanks,
Leo

**Comment by jonsulman** [comment] 2024-03-07 15:14
I built the libs from the PR and confirmed that the test code works as expected with our original pam confirmation. Thank you for following up on this!

The only issue was that `make install` put the pam libraries in `/usr/lib/security` but RHEL 8 expects them in `/usr/lib64/security`.

**Comment by dorileo** [comment] 2024-03-07 18:02
Hi @jonsulman 

That's great, thank you for testing it. About the lib path it'll be installed in the right location for rhel-8 given that the rpm packaging will "fix" it.

Thanks,
Leo

**Comment by dorileo** [comment] 2024-03-07 18:58
The PR fixing this issue was merged and it will be available on the next os login release.

Thanks,
Leo

**Closed by dorileo** 2024-03-07 18:58 UTC

**Comment by RoseSecurity** [comment] 2024-05-08 14:27
@dorileo Looks like we are still experiencing a similar issue with this. Recently upgraded to Ubuntu 22.04 and enabled `oslogin`, with the `google-guest-agent` and `google-compute-engine-oslogin` being at the latest release. We continue to see:

```sh
$ sudo su -
su: Module is unknown
```

After removing the following lines from `/etc/pam.d/su`, it works:

```plaintext
# Added by Google Compute Engine OS Login.
account    [success=bad ignore=ignore] pam_oslogin_login.so
```
