### ISSUE TITLE
OSLogin presents multiple 2FA prompts

### ISSUE THREAD

**Issue by Jawshua** [GoogleCloudPlatform/guest-oslogin#48] opened 2020-10-09 17:05 UTC
When SSHing into VMs with OSLogin and 2FA enabled, the 2FA prompt is displayed twice. It also has to be successfully passed twice to grant access.

This happens on both Ubuntu 18.04 and Debian 10 UEFI images with the Shielded VM settings enabled. It looks like this when it happens:

```
$ gcloud compute ssh <instance>
No zone specified. Using zone [europe-west4-b] for instance: [...].
Available authentication methods:
1: Google phone prompt
2: Security code from Google Authenticator application
3: Voice or text message verification code

Enter a number: 1
A login prompt has been sent to your enrolled device. Press enter to continue
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    19  100    19    0     0   1583      0 --:--:-- --:--:-- --:--:--  1583
Available authentication methods:
1: Google phone prompt
2: Security code from Google Authenticator application
3: Voice or text message verification code

Enter a number: 2
Enter your one-time password: 204649
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.0.0-1033-gcp x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Oct  9 16:53:06 UTC 2020
```

**Comment by hopkiw** [comment] 2020-10-09 17:19
There's what looks like `curl` output in the middle of this text. Is that always present when encountering the issue?
You mention shielded VM is enabled, do you mean the issue doesn't occur when not enabled?

We have automated feature validation tests on these images and I confirm that they are working. If there's something particular to your setup that causes the feature to break, I suggest filing a support request with Google Cloud Platform support.

**Comment by illfelder** [comment] 2021-01-26 22:38
I haven't seen any other issues come up with similar reports and have not been able to reproduce the issue myself. Let's close this off pending new information from @Jawshua

**Closed by illfelder** 2021-01-26 22:38 UTC
